// Purpose: Cross-platform MessageBox
// Created on: 9/12/24 @ 6:29 PM

// Copyright (c) 2024, PortalPlayer <email@portalplayer.xyz>
// Licensed under MIT <https://opensource.org/licenses/MIT>

#pragma once

typedef enum {
    BA_MESSAGEBOX_FLAG_BUTTON_OK,
    BA_MESSAGEBOX_FLAG_BUTTON_OK_CANCEL,
    BA_MESSAGEBOX_FLAG_BUTTON_ABORT_RETRY_IGNORE,
    BA_MESSAGEBOX_FLAG_BUTTON_YES_NO_CANCEL,
    BA_MESSAGEBOX_FLAG_BUTTON_YES_NO,
    BA_MESSAGEBOX_FLAG_BUTTON_RETRY_CANCEL,
    BA_MESSAGEBOX_FLAG_BUTTON_CANCEL_TRY_AGAIN_CONTINUE,

    BA_MESSAGEBOX_FLAG_ICON_ERROR = 16,
    BA_MESSAGEBOX_FLAG_ICON_QUESTION = 32,
    BA_MESSAGEBOX_FLAG_ICON_WARNING = 48,
    BA_MESSAGEBOX_FLAG_ICON_INFORMATION = 64,

    BA_MESSAGEBOX_FLAG_DEFAULT_BUTTON1 = 0,
    BA_MESSAGEBOX_FLAG_DEFAULT_BUTTON2 = 245,
    BA_MESSAGEBOX_FLAG_DEFAULT_BUTTON3 = 512,
    BA_MESSAGEBOX_FLAG_DEFAULT_BUTTON4 = 768
} BA_MessageBox_Flags;

typedef enum {
    BA_MESSAGEBOX_RESULT_OK = 1,
    BA_MESSAGEBOX_RESULT_CANCEL,
    BA_MESSAGEBOX_RESULT_ABORT,
    BA_MESSAGEBOX_RESULT_RETRY,
    BA_MESSAGEBOX_RESULT_IGNORE,
    BA_MESSAGEBOX_RESULT_YES,
    BA_MESSAGEBOX_RESULT_NO,
    BA_MESSAGEBOX_RESULT_TRY_AGAIN = 10,
    BA_MESSAGEBOX_RESULT_CONTINUE
} BA_MessageBox_Result;

BA_MessageBox_Result BA_MessageBox_Open(BA_MessageBox_Flags flags, const char* title, const char* text, ...);
