// Purpose: Safe format types
// Created on: 9/18/24 @ 9:18 PM

// Copyright (c) 2024, PortalPlayer <email@portalplayer.xyz>
// Licensed under MIT <https://opensource.org/licenses/MIT>

#pragma once

BA_CPLUSPLUS_SUPPORT_GUARD_START()
typedef enum {
    BA_STRINGSAFEFORMAT_TYPE_STRING = 1000,
    BA_STRINGSAFEFORMAT_TYPE_INTEGER,
    BA_STRINGSAFEFORMAT_TYPE_DOUBLE,
    BA_STRINGSAFEFORMAT_TYPE_CHARACTER,
    BA_STRINGSAFEFORMAT_TYPE_LONG,
    BA_STRINGSAFEFORMAT_TYPE_LONG_LONG,
    BA_STRINGSAFEFORMAT_TYPE_SHORT,
    BA_STRINGSAFEFORMAT_TYPE_UNSIGNED,
    BA_STRINGSAFEFORMAT_TYPE_LONG_DOUBLE,
    BA_STRINGSAFEFORMAT_TYPE_UNSIGNED_CHARACTER,
    BA_STRINGSAFEFORMAT_TYPE_UNSIGNED_LONG,
    BA_STRINGSAFEFORMAT_TYPE_UNSIGNED_LONG_LONG,
    BA_STRINGSAFEFORMAT_TYPE_POINTER,

    BA_STRINGSAFEFORMAT_TYPE_SIGNED = BA_STRINGSAFEFORMAT_TYPE_INTEGER,
    BA_STRINGSAFEFORMAT_TYPE_SIGNED_INTEGER = BA_STRINGSAFEFORMAT_TYPE_INTEGER,
    BA_STRINGSAFEFORMAT_TYPE_SIGNED_CHARACTER = BA_STRINGSAFEFORMAT_TYPE_CHARACTER,
    BA_STRINGSAFEFORMAT_TYPE_LONG_INTEGER = BA_STRINGSAFEFORMAT_TYPE_LONG,
    BA_STRINGSAFEFORMAT_TYPE_SIGNED_LONG = BA_STRINGSAFEFORMAT_TYPE_LONG,
    BA_STRINGSAFEFORMAT_TYPE_SIGNED_LONG_INTEGER = BA_STRINGSAFEFORMAT_TYPE_LONG,
    BA_STRINGSAFEFORMAT_TYPE_LONG_LONG_INTEGER = BA_STRINGSAFEFORMAT_TYPE_LONG_LONG,
    BA_STRINGSAFEFORMAT_TYPE_SIGNED_LONG_LONG = BA_STRINGSAFEFORMAT_TYPE_LONG_LONG,
    BA_STRINGSAFEFORMAT_TYPE_SIGNED_LONG_LONG_INTEGER = BA_STRINGSAFEFORMAT_TYPE_LONG_LONG,
    BA_STRINGSAFEFORMAT_TYPE_SHORT_INTEGER = BA_STRINGSAFEFORMAT_TYPE_SHORT,
    BA_STRINGSAFEFORMAT_TYPE_SIGNED_SHORT = BA_STRINGSAFEFORMAT_TYPE_SHORT,
    BA_STRINGSAFEFORMAT_TYPE_SIGNED_SHORT_INTEGER = BA_STRINGSAFEFORMAT_TYPE_SHORT,
    BA_STRINGSAFEFORMAT_TYPE_UNSIGNED_INTEGER = BA_STRINGSAFEFORMAT_TYPE_UNSIGNED,
    BA_STRINGSAFEFORMAT_TYPE_UNSIGNED_LONG_INTEGER = BA_STRINGSAFEFORMAT_TYPE_UNSIGNED_LONG,
    BA_STRINGSAFEFORMAT_TYPE_UNSIGNED_LONG_LONG_INTEGER = BA_STRINGSAFEFORMAT_TYPE_UNSIGNED_LONG_LONG
} BA_StringSafeFormat_Types;

typedef void* (*BA_StringSafeFormat_CustomSafeFormatAction)(void* buffer, BA_Boolean fromWideCharacter, void** argument);

BA_Boolean BA_StringSafeFormat_AddCustomSafeFormatter(int identifier, BA_StringSafeFormat_CustomSafeFormatAction actionFunction);
BA_CPLUSPLUS_SUPPORT_GUARD_END()

#define BA_STRINGSAFEFORMAT_ARGUMENT_STRING(value) BA_STRINGSAFEFORMAT_TYPE_STRING, value
#define BA_STRINGSAFEFORMAT_ARGUMENT_INTEGER(value) BA_STRINGSAFEFORMAT_TYPE_INTEGER, value

/**
 * Requires a decimal point, even if the number after is just zero
 */
#define BA_STRINGSAFEFORMAT_ARGUMENT_DOUBLE(value) BA_STRINGSAFEFORMAT_TYPE_DOUBLE, value
#define BA_STRINGSAFEFORMAT_ARGUMENT_CHARACTER(value) BA_STRINGSAFEFORMAT_TYPE_CHARACTER, value
#define BA_STRINGSAFEFORMAT_ARGUMENT_LONG(value) BA_STRINGSAFEFORMAT_TYPE_LONG, value
#define BA_STRINGSAFEFORMAT_ARGUMENT_LONG_LONG(value) BA_STRINGSAFEFORMAT_TYPE_LONG_LONG, value
#define BA_STRINGSAFEFORMAT_ARGUMENT_UNSIGNED(value) BA_STRINGSAFEFORMAT_TYPE_UNSIGNED, value

/**
 * Requires a decimal point, and the suffix: l
 */
#define BA_STRINGSAFEFORMAT_ARGUMENT_LONG_DOUBLE(value) BA_STRINGSAFEFORMAT_TYPE_LONG_DOUBLE, value
#define BA_STRINGSAFEFORMAT_ARGUMENT_UNSIGNED_CHARACTER(value) BA_STRINGSAFEFORMAT_TYPE_UNSIGNED_CHARACTER, value
#define BA_STRINGSAFEFORMAT_ARGUMENT_UNSIGNED_LONG(value) BA_STRINGSAFEFORMAT_TYPE_UNSIGNED_LONG, value
#define BA_STRINGSAFEFORMAT_ARGUMENT_UNSIGNED_LONG_LONG(value) BA_STRINGSAFEFORMAT_TYPE_UNSIGNED_LONG_LONG, value
#define BA_STRINGSAFEFORMAT_ARGUMENT_POINTER(value) BA_STRINGSAFEFORMAT_TYPE_POINTER, value

#define BA_STRINGSAFEFORMAT_ARGUMENT_SIGNED(value) BA_STRINGSAFEFORMAT_ARGUMENT_INTEGER(value)
#define BA_STRINGSAFEFORMAT_ARGUMENT_SIGNED_INTEGER(value) BA_STRINGSAFEFORMAT_ARGUMENT_INTEGER(value)
#define BA_STRINGSAFEFORMAT_ARGUMENT_SIGNED_CHARACTER(value) BA_STRINGSAFEFORMAT_ARGUMENT_CHARACTER(value)
#define BA_STRINGSAFEFORMAT_ARGUMENT_LONG_INTEGER(value) BA_STRINGSAFEFORMAT_ARGUMENT_LONG(value)
#define BA_STRINGSAFEFORMAT_ARGUMENT_SIGNED_LONG(value) BA_STRINGSAFEFORMAT_ARGUMENT_LONG(value)
#define BA_STRINGSAFEFORMAT_ARGUMENT_SIGNED_LONG_INTEGER(value) BA_STRINGSAFEFORMAT_ARGUMENT_LONG(value)
#define BA_STRINGSAFEFORMAT_ARGUMENT_LONG_LONG_INTEGER(value) BA_STRINGSAFEFORMAT_ARGUMENT_LONG_LONG(value)
#define BA_STRINGSAFEFORMAT_ARGUMENT_SIGNED_LONG_LONG(value) BA_STRINGSAFEFORMAT_ARGUMENT_LONG_LONG(value)
#define BA_STRINGSAFEFORMAT_ARGUMENT_SIGNED_LONG_LONG_INTEGER(value) BA_STRINGSAFEFORMAT_ARGUMENT_LONG_LONG(value)
#define BA_STRINGSAFEFORMAT_ARGUMENT_UNSIGNED_INTEGER(value) BA_STRINGSAFEFORMAT_ARGUMENT_UNSIGNED(value)
#define BA_STRINGSAFEFORMAT_ARGUMENT_UNSIGNED_LONG_INTEGER(value) BA_STRINGSAFEFORMAT_ARGUMENT_UNSIGNED_LONG(value)
#define BA_STRINGSAFEFORMAT_ARGUMENT_UNSIGNED_LONG_LONG_INTEGER(value) BA_STRINGSAFEFORMAT_ARGUMENT_UNSIGNED_LONG_LONG(value)
