macro(ba_apply_compiler_options TARGET)
    if(CMAKE_BUILD_TYPE STREQUAL "Debug" OR CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
        target_compile_definitions("${TARGET}" PUBLIC DEBUG BA_ALLOW_DEBUG_LOGS)
    elseif(BA_ALLOW_DEBUG_LOGS)
        target_compile_definitions("${TARGET}" PUBLIC BA_ALLOW_DEBUG_LOGS)
    endif()
    
    if(BA_ALLOW_DEBUG_LOGS)
        target_compile_definitions("${TARGET}" PUBLIC BA_ALLOW_DEBUG_LOGS)
    endif()

    if(BA_SINGLE_THREADED)
        target_compile_definitions("${TARGET}" PUBLIC BA_SINGLE_THREADED)
    endif()
endmacro()